name: Documentation/Misc Task
description: File a task for something related to this repo, but not actually inside the project source code - e.g., for someone to document something here on GitHub, or to update one of the support tools.
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the task and your desired outcome. Do include any relevant screenshots at suitable locations in the body of your text.
    validations:
      required: true
      
